name: GitHub Actions - Teste com dependência Template
run-name: Running - Teste com dependência Template
on: [push, workflow_dispatch]
env:
  variavel: "Bom dia"
  var_1: ${{secrets.TEST_SECRET}}
  var_2: ${{vars.VAR_TEST}}
jobs:
  Setup:
    runs-on: ubuntu-20.04
    steps:
      - name: Comentário
        run: |
          echo "Execução Setup"
  test_api:
    needs: Setup
    runs-on: ubuntu-20.04
    steps:
      - name: Comentário
        run: |
          echo "Execução test"
  test_ui:
    needs: [Setup, test_api]
    runs-on: ubuntu-20.04
    steps:
      - name: Comentário
        run: |
          echo "Execução test"