name: GitHub Actions - Input String Workflow Dispatch - Branch Template
run-name: Running - ${{ github.event_name }}
on:
  workflow_dispatch:
    inputs:
      browser:
        description: Selecione o Browser
        type: string
jobs:
  on-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Comentário
        run: |
          echo "Comentário Workflow dispatch - Browser: ${{inputs.browser}}"