name: GitHub Actions - Push - Branch Template
run-name: Running ${{github.event_name}}
on: 
    push:
        branches:
         - develop
jobs:
    on-push:
        runs-on: ubuntu-latest
        steps:
            - name: Comentário
              run: |
                echo "comentário do Workflow PUSH"