name: GitHub Actions - Matrix Strategy Template
run-name: Running - Matrix
on: [push, workflow_dispatch]

jobs:
  Matrix_job:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        navegador: [chrome, firefox, webkit]
      fail-fast: false
    steps:
      - name: Comentário
        run: |
          echo ${{matrix.navegador}}
  